<?php

namespace JiSight\Message\Facades;

use Illuminate\Support\Facades\Facade;

class Message extends Facade
{

    protected static function getFacadeAccessor()
    {

//        return

//        parent::getFacadeAccessor(); // TODO: Change the autogenerated stub
    }

}